### ISSUE TITLE
Collecters gift charm not making?

### ISSUE THREAD

**Issue by PDuckGit** [masik16u/Mythic-Charms#17]
I put in every single item that's required to craft it on a table, i threw a bottle of xp and nothing happened. the charm is enabled and we put everything needed on the table. We also already have a resonance ring and a block of lapis underneath? Anybody know why its not working? (For Multiplayer Btw).

**Comment by masik16u** [comment]
Are there any other mods installed? And is it a mod pack?

**Comment by PDuckGit** [comment]
It turned out we ended up throwing it wrong, but it still was inconsistent. We ended up not using the modpack anymore.
