### ISSUE TITLE
[Version Request] for 1.20.1

### ISSUE THREAD

**Issue by xR4YM0ND** [masik16u/Mythic-Charms#2]
Could you backport this awesome mod for 1.20.1?

Shouldnt be that changing than 1.19 or 1.18

And can we disable certain charms via config completely?

**Comment by masik16u** [comment]
Sure, if everything won't go south I will add the 1.20.1 version of the mod

Configs are planned but not currently in the mod

**Comment by xR4YM0ND** [comment]
Awesome to hear, looking forward to the config update ^^

**Comment by masik16u** [comment]
Backport done :D, now to the configs. I want to hear your thoughts as a modpack creator, a lot of things can be added to the configs but what are the most crucial ones? Would disabling charms be enough?

**Comment by xR4YM0ND** [comment]
Awesome <3

I havent yet played this mod.

Let me try it when im home and i let you know my thoughts here.

**Comment by xR4YM0ND** [comment]
So i tried the mod and i thought the table had a gui but nanana ^^

I'm a person who likes open / modular - e.g. data driven things / config option for everything

But yeah if you would do all rune recipes data driven (e.g. TieredZ mod) we could change different aspects of some runes or maybe remove some effects & give them other ones. 
We would also be able to change the recipe for those all via datapack.
And then a simple config that just has options for every rune to disable it.

But if the data driven (datapack) thing isn't something for you, then a simple config for all charms would be enough.
(I recommend Cloth Config with json5)

Also pls make REI optional ( if you support EMI / JEI in future these pls optional as well ^^ <3 )


& I found it kinda hard to land the items on the table -> what do you think about the way Botania made them float and stuck to the table ?

That should be all for now ^^ Love your mods and keep up the awesome work! <3

**Comment by masik16u** [comment]
I will see what I can do about data-driven crafts

I will use owo-lib for config as I'm already using this library

REI is already optional :)

Yeah, I will think what I can do with the table

Thanks for the feedback! <3

**Comment by xR4YM0ND** [comment]
Your welcome!

Yeah but still its tagged as required so in launchers the required dependencies get automatically installed

**Comment by xR4YM0ND** [comment]
Yep

**Comment by xR4YM0ND** [comment]
Ah perfect thank you <3

**Comment by masik16u** [comment]
Finally, I added data-driven crafting after all this time. Now I can close this issue :)
