### ISSUE TITLE
Drowned Freedom doesn't allow conduit power to work

### ISSUE THREAD

**Issue by catreplicators** [masik16u/Mythic-Charms#20]
I don't get conduit power when using Drowned Freedom, despite the presence of a source of the Conduit Power effect.
This might just be an issue with Botania's ring of chordata, but compatibility with that is also an (admittedly minor) issue.

**Comment by masik16u** [comment]
I think that's the problem with Drowned Freedom and how it works. That will be really good combo, I will most likely fix it in the next update :)
