### ISSUE TITLE
[Feature Request] EMI Support

### ISSUE THREAD

**Issue by TheTrueYak** [masik16u/Mythic-Charms#3]
Is there support planned for EMI? (Alternative to REI)

I use EMI because it is (in my opinion) better and more featureful than REI, and it is frustrating to be unable to view the recipes of the charms simply because I am not using REI.

Just curious if there will be any EMI support in the future.

**Comment by masik16u** [comment]
Sure, I will add it, If I figure out how to do this

**Comment by TheTrueYak** [comment]
Thanks, appreciate it

**Comment by xR4YM0ND** [comment]
Pls make REI optional tho, cause yeah for people who use EMI or JEI its frustrating to have both.

~ i love EMI ^^

**Comment by masik16u** [comment]
It is already optional, but because there is no other way to see crafts I marked it as required
